# Generated by Django 3.0.5 on 2020-05-28 12:43
import os
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_appuser_delivery_at'),
    ]

    def generate_superuser(apps, schema_editor):
        from ..models import AppUser

        DJANGO_DB_NAME = os.environ.get('DJANGO_DB_NAME', "default")
        DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL', "admin@admin.com")
        DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD', "admin")

        superuser = AppUser.objects.create_superuser(
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD)

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
