# Generated by Django 3.0.5 on 2020-05-30 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appuser_delivery_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='delivery_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 9, 33, 32, 574368, tzinfo=utc)),
        ),
    ]
