# Generated by Django 3.0.5 on 2020-05-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precedent',
            old_name='sign',
            new_name='attitude',
        ),
    ]
