# Generated by Django 3.0.5 on 2020-05-30 09:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200527_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precedent',
            name='importance',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='precedent',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedents', to='api.Participant'),
        ),
    ]
