# Generated by Django 3.0.5 on 2020-06-11 03:19

import api.models
from django.db import migrations, models


def migrate_importance(apps, schema_editor):
    model = apps.get_model('api', 'precedent')

    for item in model.objects.all():
        item.importance = -item.importance if item.attitude == 0 else item.importance
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200604_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precedent',
            name='importance',
            field=models.SmallIntegerField(validators=[api.models.importance_validator]),
        ),
        migrations.RunPython(migrate_importance),
    ]
