# Generated by Django 3.0.5 on 2020-06-11 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200611_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precedent',
            name='attitude',
        ),
    ]
